version: '3'

services:
  consul-server:
    image: consul:latest
    hostname: consul-server
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  whoami:
    build: ./whoami
    depends_on:
      - consul-server
    networks:
      - consul-demo
  bar:
    build: ./bar
    depends_on:
      - consul-server
      - whoami
    networks:
      - consul-demo
    ports:
      - "9090:80"

networks:
  consul-demo:
